name: Pack CONTOSO-UNIVERSITY
on:
    push:
        paths:
            -contents/**
    workflow_dispatch:

jobs:
  build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: microsoft/powerplatform-actions/pack-solution@v0
              with:
                    solution-file: out/ManualExport.zip
                    solution-folder: contents
            - uses: actions/upload-artifact@v2
              with:
                    name: packed-solution
                    path: out/

